site:
  title: Adarsh | Senior Technical Writer Portfolio
  start_page: adarsh-tech-docs-portfolio-repo::index.adoc
  # url: https://adarshbm32.gitlab.io/learn-site

content:
  sources:
    - url: ./workspace/adarsh-tech-docs-portfolio-repo
      branches: HEAD

asciidoc:
  attributes:
    full-name: Adarsh BM
    role: Senior Technical Writer
    professional-email: adarshbm@example.com
    sectnums: ""
    sectnumlevels: 3
    idprefix: ""
    idseparator: "-"
    sectanchors: ""
    icons: font
    toc: ~
    experimental: ""
    allow-uri-read: ""

  extensions:
    - asciidoctor-kroki
    - '@asciidoctor/tabs'
    - asciidoctor-external-callout

antora:
  extensions:
    - require: '@antora/lunr-extension'
      index_latest_only: true
      languages: [en]
      snippet_length: 250
      index_by_heading: true

    - require: '@antora/pdf-extension'
    - require: '@antora/collector-extension'

    # Your custom search behavior
    - require: ./extensions/search-index-customizer.js
    - require: ./extensions/lunr-enhancements-extension.js

ui:
  bundle:
    url: ./ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./build/site
  clean: true

runtime:
  fetch: true
